### ISSUE TITLE
Setup instructions based on claw-playbook

### ISSUE THREAD

**Issue by seth-shaw-unlv** [mjordan/riprap#20]
Given a vagrant up of claw playbook, how would we set up riprap to audit the included Fedora repository?

**Comment by mjordan** [comment]
@seth-shaw-unlv there is one piece missing that is required to put Riprap into production - a "fetchresourcelist" plugin to generate a list of resources to check. #14 and #6 address this. I have done some work on #14 (which would have the jsonapi module as a dependency) since to begin with, I think it makes sense to use Drupal as the source of the list of resources to check.

I'll start some concrete work on the Riprap plugin this week. Then we'll be in a position to document setting it up with a CLAW playbook.

**Comment by mjordan** [comment]
@seth-shaw-unlv making good progress on a "fetchresourcelist" plugin to generate a list of resources. See #14 for details. Need to convert Drupal URLs for media files to Fedora URLs, which I should get to today.

**Comment by mjordan** [comment]
@seth-shaw-unlv thanks for your patience.

Here's a rough draft. It assumes you are running a CLAW Playbook with fcrepo 5.

1. Install Riprap on your Vagrant guest following the instructions in the Riprap readme, but don't bother loading the sample data, e.g., skip the `php bin/console -n doctrine:fixtures:load` command.
1. The default config should work for you, but to be sure, look at lines 14-27 in `config/services.yaml` and adjust accordingly.
1. To populate Riprap's database with fixity events on media in your CLAW Playbook instance, run the check fixity command a few times, a couple of minutes apart, e.g. `php bin/console app:riprap:check_fixity`. Each time you run this command, it will tell you how many fixity checks it performed.
1. Start the built-in Symfony web server by running `php bin/console server:start *:8001`. This will provide a REST endpoint at `http://localhost:8001/api/fixity`.
1. Install and configure https://github.com/mjordan/islandora_riprap to get media-level reports from within Drupal. Since you want to run Riprap on the Vagrant guest, you should use `http://localhost:8001/api/fixity` in the "Riprap microservice REST endpoint" config setting.

**Comment by mjordan** [comment]
@seth-shaw-unlv I have added a bunch of content to the Riprap README that should cover this. Please let me know what you think.

**Comment by seth-shaw-unlv** [comment]
Thanks, @mjordan! I will take a look at it sometime this week.

**Comment by mjordan** [comment]
Cool. I just edited the instructions above to reflect some work I did yesterday.

**Comment by seth-shaw-unlv** [comment]
On CentOS, 
- I cloned the application to `/opt/riprap`
- `cp config/services.yaml.islandora config/services.yaml`. Everything looked good, so I didn't change anything
- `composer install`
- Database
  - created a MySQL user 'riprap'
  - updated the doctrine.yaml file
  - updated the .env file
  - migrated the database

So far, so good. 

I ran `php bin/console app:riprap:check_fixity` and was notified:
```
In PluginFetchResourceListFromDrupal.php line 123:
                                                                                       
  Warning: count(): Parameter must be an array or an object that implements Countable  
```
I ran it again, verbosely, and was additionally given the stack trace:
```
Exception trace:
 App\Command\PluginFetchResourceListFromDrupal->execute() at /opt/riprap/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /opt/riprap/src/Command/CheckFixityCommand.php:70
 App\Command\CheckFixityCommand->execute() at /opt/riprap/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /opt/riprap/vendor/symfony/console/Application.php:904
 Symfony\Component\Console\Application->doRunCommand() at /opt/riprap/vendor/symfony/framework-bundle/Console/Application.php:89
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /opt/riprap/vendor/symfony/console/Application.php:262
 Symfony\Component\Console\Application->doRun() at /opt/riprap/vendor/symfony/framework-bundle/Console/Application.php:75
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /opt/riprap/vendor/symfony/console/Application.php:145
 Symfony\Component\Console\Application->run() at /opt/riprap/bin/console:39
```

So, `$node_list_array['data']` doesn't appear to be an array, but it must be *something* because it didn't throw a key error. Any idea what is going on or how I should debug this?

**Comment by mjordan** [comment]
Did you start the Symfony web server?

**Comment by seth-shaw-unlv** [comment]
Maybe this is a Drupal configuration issue. `curl -I http://localhost:8000/jsonapi/node/islandora_object` responds with a 404.

**Comment by seth-shaw-unlv** [comment]
Not yet, it was your step 5 when I was on 4.

**Comment by seth-shaw-unlv** [comment]
I've started it now (`php bin/console server:start *:8001`). No change in the error when running the fixity check.

**Comment by mjordan** [comment]
How about installing https://www.drupal.org/project/jsonapi and enabling it? I didn't include that step above, but it is in the Riprap README.... which is long and detailed.

**Comment by seth-shaw-unlv** [comment]
There we go. I needed to composer require drupal/jsonapi and enable it. Now it is working.

**Comment by seth-shaw-unlv** [comment]
Ah. I see now. I inferred from the readme that it was a core module that would already be available, not something I needed to install separately. The readme should probably link to the JSON:API project page.

**Comment by mjordan** [comment]
Yeah. Any suggestions like that are useful. Let me do that. Once you've installed JSON:API, let me know how it goes.

**Comment by mjordan** [comment]
@seth-shaw-unlv closing this, reopen if needed.
